/*
===========================================================================

Return to Castle Wolfenstein single player GPL Source Code
Copyright (C) 1999-2010 id Software LLC, a ZeniMax Media company.

This file is part of the Return to Castle Wolfenstein single player GPL Source Code (RTCW SP Source Code).

RTCW SP Source Code is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

RTCW SP Source Code is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with RTCW SP Source Code.  If not, see <http://www.gnu.org/licenses/>.

In addition, the RTCW SP Source Code is also subject to certain additional terms. You should have received a copy of these additional terms immediately following the terms and conditions of the GNU
General Public License which accompanied the RTCW SP Source Code.  If not, please request a copy in writing from id Software at the address below.

If you have questions concerning this license or the applicable additional terms, you may contact in writing id Software LLC, c/o ZeniMax Media Inc., Suite 120, Rockville, Maryland 20850 USA.

===========================================================================
*/

/*!
	\file engine/botlib/l_log.h
	\brief 	This module implements a simple logging subsystem for the bot library, providing file I/O, timestamped writes, and lifecycle management.
	\note doxygenix: sha256=2bfb25d0ffc45b33cd51430efe9dabdb6da96c96e6d3947fc3af39d5ca2aa911

	\par File Purpose
	- 	This module implements a simple logging subsystem for the bot library, providing file I/O, timestamped writes, and lifecycle management.

	\par Core Responsibilities
	- 	- Manage the lifetime of the log file used by botlib functions;
	- 	- Provide formatted logging routines with optional timestamping;
	- 	- Centralize error handling for missing or failed log operations;
	- 	- Expose the underlying FILE* for legacy or lower‑level use;
	- 	- Ensure that log output is flushed immediately to disk.

	\par Key Types and Functions
	- Log_Open(char* filename) — opens a log file when logging is enabled;
	- Log_AlwaysOpen(char* filename) — opens a log file for writing if none is open and initializes global state;
	- Log_Close() — closes the current log file if open;
	- Log_Shutdown() — shuts down logging by calling Log_Close;
	- Log_Write(char* fmt, ...) — writes a formatted message to the log file without a newline;
	- Log_WriteTimeStamped(char* fmt, ...) — writes a timestamped, counter‑prefixed entry followed by CRLF;
	- Log_FilePointer() — returns the FILE* currently open for logging;
	- Log_Flush() — forces the logfile buffer to be written to disk.

	\par Control Flow
	- Log_Open checks a config variable and delegates to Log_AlwaysOpen if logging is enabled; Log_AlwaysOpen opens the file, populates global logfile structure, and reports success or failure; Log_Close and Log_Shutdown close an open logfile and reset the global handle; Log_Write outputs formatted strings to the logfile using vfprintf and flushes the stream; Log_WriteTimeStamped prefixes each entry with a counter and timestamp derived from botlibglobals.time, then writes and flushes; Log_FilePointer returns the raw FILE* for external use; Log_Flush calls fflush on the current logfile pointer if valid.

	\par Dependencies
	- 	- Standard C library <stdio.h> for FILE, vfprintf, fflush;
	- 	- Bot library globals for time tracking (botlibglobals.time);
	- 	- Config variable handling (e.g., CVar value 'log');
	- 	- Error printing via botimport.Print;
	- 	- Constants such as MAX_LOGFILENAMESIZE.

	\par How It Fits
	- 	Acts as the I/O backend for diagnostic output generated by bot logic;
	- 	Keeps bot logs separate from console or engine logs;
	- 	Relies on global botlib state for time and configuration;
	- 	Provides a minimal, portable logging API that avoids dependencies on external logging frameworks.
*/

/*****************************************************************************
 * name:		l_log.h
 *
 * desc:		log file
 *
 *
 *****************************************************************************/

/*!
	\brief Opens a log file when logging is enabled.

	The function first checks if logging is activated by querying the configuration variable "log"; if logging is disabled it exits immediately. When logging is enabled it delegates to Log_AlwaysOpen
   to actually open the file specified by the filename argument.

	\param filename the full path to the log file to be opened
*/
void	   Log_Open( char* filename );

/*!
	\brief Opens a log file for writing if one is not already open

	If the supplied filename is null or empty, the function prints a usage message and returns.  If a log file is already open, an error message is printed and the function exits.  The function
   attempts to open the file in binary write mode; failure to open results in an error message.  On success, the global logfile structure is populated with the file pointer and the filename (truncated
   to MAX_LOGFILENAMESIZE characters).  Informational output confirms the file that was opened.

	\param filename Path of the file to open
*/
void	   Log_AlwaysOpen( char* filename );

/*!
	\brief Closes the current log file, if one is open.

	When called, the function first checks whether a file pointer is active. If not, it simply exits. Otherwise it attempts to close the file. If the close operation fails, an error message is printed
   via botimport.Print, and the function returns immediately. If the close succeeds, the file pointer is cleared and a message confirming the closure is output.

*/
void	   Log_Close();

/*!
	\brief Shuts down the logging system by closing the log file if it is open.

	The function checks whether the global log file pointer has been initialized and, if so, calls Log_Close to close the file. If the file was never opened, no action is taken.

*/
void	   Log_Shutdown();

/*!
	\brief Writes a formatted message to the current log file if it is open.

	The function accepts a printf‑style format string followed by a variable number of arguments. It first checks whether the global logfile handle is valid; if not, it simply returns. When the file
   is open, the function uses vfprintf to output the formatted text to the file and then flushes the stream to ensure the data is written immediately. The implementation deliberately omits an
   automatic newline, leaving any necessary characters to be provided explicitly by the caller.

	\param fmt Printf‑style format string that specifies how the remaining arguments should be formatted.
*/
void QDECL Log_Write( char* fmt, ... );

/*!
	\brief Writes a formatted message to the current log file, prefixed with a write counter and timestamp.

	If the log file is not open, the function returns without doing anything.
	The timestamp is printed as <write count>   HH:MM:SS:CC   where HH is hours since start, MM minutes, SS seconds, and CC hundredths of a second derived from botlibglobals.time.
	After the timestamp, the supplied format string is printed with the variable arguments.
	A carriage return and line feed are appended, the counter is incremented, and the output is flushed to ensure durability.

	\param fmt Format string used with vfprintf; it may contain format specifiers supported by printf.
*/
void QDECL Log_WriteTimeStamped( char* fmt, ... );

/*!
	\brief Returns a pointer to the log file used by the logging system.

	The function retrieves the FILE* stored in the global logfile structure. The returned pointer is used throughout the codebase for writing log entries. It may be NULL if the log file has not yet
   been initialized or if it was closed.

	\return a FILE* pointing to the log file or NULL if unavailable
*/
FILE*	   Log_FilePointer();

/*!
	\brief Flushes the opened log file to disk.

	If the log file has been successfully opened, the function calls fflush on its file pointer to ensure all buffered output is written to the underlying file. No operation is performed when the file
   pointer is null.

*/
void	   Log_Flush();
